name: pluto
version: '1.0'
main: de.jdevr.pluto.Pluto
api-version: '1.21.1'
depend:
  - Multiverse-Core
  - Multiverse-Inventories
commands:
  hub:
    description: "Bringt dich zum hub!"
  menu:
    description: "Öffnet das Menü!"
  marker:
    description: "Plaziert einen Marker"
  placewalk:
    description: "Plaziert einen bestimmten block unter dir!"
  autofill:
    description: "Fülle ein gebiet"
  lastdeath:
    description: "Letzter Tod"
permissions:
  permissions.modworld:
    description: Erlaubt das modifizieren von Welten
    default: op
    children:
      permissions.tpworld: true
