name: pluto
version: '1.0'
main: de.jdevr.pluto.Pluto
api-version: '1.21'
commands:
  createworld:
    description: Erstellt eine neue Welt
    permission: permissions.modworlds
  tpworld:
    description: Teleportiert den Spieler auf eine Welt
    permission: permissions.tpworld
  deleteworld:
    description: Löscht eine Welt
    permission: permissions.modworld
  listworlds:
    description: Zeigt alle Welten an
    permission: permissions.listworlds
permissions:
  permissions.modworld:
    description: Erlaubt das modifizieren von Welten
    default: op
    children:
      permissions.tpworld: true