name: pluto
version: '1.0-SNAPSHOT'
main: de.jdevr.pluto.Pluto
api-version: '1.21'
commands:
  createworld:
    description: Erstellt eine neue Welt
    permission: permissions.modworlds
  tpworld:
    description: Teleportiert den Spieler auf eine Welt
    permission: permissions.tp
  deleteworld:
    description: Löscht eine Welt
    permission: permissions.modworld
permissions:
